### ISSUE TITLE
View by project

### ISSUE THREAD

**Issue by dtamajon** [twinslash/redmine_all_files#12]
Hi!

I think would be nice to view files filtered by project. And sure it will reduce problems when having a huge amount of files distributed in different projects.

PD: I'm using your plugin on Redmine 2.6 and its working properly.

**Comment by Peneheals** [comment]
You are able to view the files connected to a project: Enable the module in any projects where you want to list the attached files (settings -> modules page -> tick All files), then you can view the list at example.com/project_attachments?project_id=PROJECT_NAME

**Comment by dtamajon** [comment]
I have checked and works as you describes.

Thank you
